In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
#creating array
n_array = np.array([1,2,3,4,5])

In [5]:
n_array

array([1, 2, 3, 4, 5])

In [6]:
#2d array
ary2 = np.array([[1,2,3,4,5], [5,4,3,2,1]])

In [7]:
ary2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [8]:
np.array([1,1,1,1,1])

array([1, 1, 1, 1, 1])

In [9]:
np.array(np.ones(5))

array([1., 1., 1., 1., 1.])

In [10]:
np.array(np.zeros(4))

array([0., 0., 0., 0.])

In [11]:
print("An identity matrix size 5")
print(np.eye(5))

An identity matrix size 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
np.arange(2,50,3) #Array from 2 to 50 skipping by 3

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [13]:
#Indexing in array
arr = np.arange(0,10,1)
print(arr)
print(arr[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [14]:
print(arr[0:6])

[0 1 2 3 4 5]


In [15]:
print("elements change 0:6 -> 20")
arr[0:6] = 20

elements change 0:6 -> 20


In [16]:
arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9])

In [17]:
#slicing array
slc_array = arr[2:6]
slc_array

array([20, 20, 20, 20])

In [18]:
new_arr = arr[:]
new_arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9])

In [19]:
#indexing for 2d array
#declare
array_2d = np.array([[1,2,3],[4,5,6],[1,24,56]])

In [20]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1, 24, 56]])

In [21]:
print("selecting 0 row 1st column")
print(array_2d[0][1])

selecting 0 row 1st column
2


In [22]:
print(array_2d[1:3, 1:3])
#1st '[1:3]' are rows, 2nd '[1:3]' are columns.
#Remember that in '[1:3]' the '3' is not the column 3,
# is column 4 but because of the range's beheaviour it doesnt count 

[[ 5  6]
 [24 56]]


In [23]:
array_2d[1:3, 1:3] = 20
print(array_2d)

[[ 1  2  3]
 [ 4 20 20]
 [ 1 20 20]]


In [24]:
print(array_2d[:, 1:2])

[[ 2]
 [20]
 [20]]


In [25]:
arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9])

In [26]:
new_arr = arr[1:7].copy()
print(new_arr)

[20 20 20 20 20  6]


In [27]:
new_arr[:] = 30

In [28]:
arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9])

In [29]:
new_arr

array([30, 30, 30, 30, 30, 30])

In [30]:
#transposing array
arr = np.arange(0,50,1).reshape(10,5)

In [31]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [32]:
print(arr.transpose()) 
# Matriz transpuesta

[[ 0  5 10 15 20 25 30 35 40 45]
 [ 1  6 11 16 21 26 31 36 41 46]
 [ 2  7 12 17 22 27 32 37 42 47]
 [ 3  8 13 18 23 28 33 38 43 48]
 [ 4  9 14 19 24 29 34 39 44 49]]


In [33]:
arr1 = np.arange(1,40,4)
arr2= np.arange(1,30,3)

In [34]:
arr1

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

In [35]:
arr2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [36]:
np.exp(arr1)
# Calcula e^x para cada valor del array siendo x

array([2.71828183e+00, 1.48413159e+02, 8.10308393e+03, 4.42413392e+05,
       2.41549528e+07, 1.31881573e+09, 7.20048993e+10, 3.93133430e+12,
       2.14643580e+14, 1.17191424e+16])

In [37]:
(2.71828183)*(2.71828183)*(2.71828183)*(2.71828183)*(2.71828183)

148.413159523243

In [38]:
np.square(arr1)
#Hace un map de x**2 por cada valor del array siendo x

array([   1,   25,   81,  169,  289,  441,  625,  841, 1089, 1369])

In [39]:
np.sqrt(arr1)
#Hace un map de x**1/2 por cada valor del array siendo x

array([1.        , 2.23606798, 3.        , 3.60555128, 4.12310563,
       4.58257569, 5.        , 5.38516481, 5.74456265, 6.08276253])

In [40]:
np.cbrt(arr1)
#Hace un map de x**1/3 por cada valor del array siendo x

array([1.        , 1.70997595, 2.08008382, 2.35133469, 2.57128159,
       2.75892418, 2.92401774, 3.07231683, 3.20753433, 3.33222185])

In [41]:
arr1

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

In [42]:
arr2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [43]:
np.add(arr1, arr2)
#Suma cada valor de (x + y) y lo guarda en la posicion correspondiente

array([ 2,  9, 16, 23, 30, 37, 44, 51, 58, 65])

In [44]:
np.subtract(arr1, arr2)
#Resta cada valor de (x - y) y lo guarda en la posicion correspondiente

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([500,600,700,800])
cond = np.array([False, True, False, True])
res = np.where(cond, arr1, arr2)
print(res)
#Si es False aggara del 2do array, si es True agarra del 1er array

[500  20 700  40]


In [46]:
arr1=np.random.rand(7)
arr2=np.array(["dog", "cat", "lion"])

In [47]:
arr1

array([0.96726342, 0.32082103, 0.45676044, 0.14198674, 0.74395328,
       0.72842677, 0.34356514])

In [48]:
arr1.mean()

0.5289681160940788

In [49]:
sum(arr1)/len(arr1)

0.5289681160940788

In [50]:
arr1.var()

0.07296759383386396

In [51]:
arr1.std()

0.2701251447641703

In [52]:
arr1.sum()

3.702776812658551

In [53]:
arr1.sort()

In [54]:
arr1

array([0.14198674, 0.32082103, 0.34356514, 0.45676044, 0.72842677,
       0.74395328, 0.96726342])

In [55]:
np.unique(arr2)

array(['cat', 'dog', 'lion'], dtype='<U4')

In [56]:
arr2

array(['dog', 'cat', 'lion'], dtype='<U4')

In [57]:
#------------------------FIRST ASSIGNMENT---------------------
assgn_arr = np.array([[-3,0,5,-6],
                      [7, 2, -1, 9],
                      [12, -4, 3, 1]
                     ])

In [62]:
np.amax(assgn_arr) #Returns max value in array
np.where(assgn_arr == np.amin(assgn_arr)) #Returns (minimum value, minimum value index)

12

In [67]:
def getMinMax(arr):
    """Get the minimum and maximum value for each row in a single list [a1Min, a1Max, a2Min, a2Max,...]"""
    min_max_arr = []
    for row in arr:
        min_max_arr += [np.amin(row), np.amax(row)]
    return min_max_arr

In [68]:
getMinMax(assgn_arr)

[-6, 5, -1, 9, -4, 12]

In [69]:
#--------------------FIRST ASSIGNMENT FINISHED-----------------

In [76]:
# Get the minimum values of each column i.e. along axis 0
minInColumns = np.amin(assgn_arr, axis=0)
# Get the minimum values of each row i.e. along axis 1
minInRows = np.amin(assgn_arr, axis=1)
# The same applies for amax
print(f"Minimum values in Columns: {minInColumns}\nMinimum values in Rows: {minInRows}")

Minimum values in Columns: [-3 -4 -1 -6]
Minimum values in Rows: [-6 -1 -4]


In [82]:
# Generates a random matrix with values from 1 to 100 in a 5 rows x 5 columns matrix
np.random.randint(1, 100, size=(5,5))

array([[94, 88, 78, 20, 92],
       [43, 33, 18, 15, 41],
       [ 6,  4, 30, 17, 71],
       [83, 14, 15, 95, 42],
       [43, 71, 92, 99, 10]])